### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by epuscasu** [kevin-keraudren/chanvese#1]
What is the license associated with this project? I would like to use it as a part of a bigger project (plant recognition)

**Comment by kevin-keraudren** [comment]
The code is a Python translation of the Matlab code from CREASEG, whose license has been copied there:
https://github.com/kevin-keraudren/chanvese/blob/master/creaseg/license.txt

I added an MIT license for the Python code so you can do whatever you want with it.
